### PR TITLE
Refactor time formatting and default CloudLogger to a Loggly compatible format

### PR DESCRIPTION
**Pull request by Aelazr**

### CODE REVIEW

**Review by colinc86 — APPROVED** [review]

**Review by GregWWalters — APPROVED** [review]
I like the implementation, but was there a need to have a time format that _isn't_ the one for Loggly?

**Comment by Aelazr** [comment]
> I like the implementation, but was there a need to have a time format that _isn't_ the one for Loggly?

I was just keeping the original implementation. If no one wants it, I can take it out

**Comment by colinc86** [comment]
I 2nd Greg. I think the loggly-approved time format is good. Especially with the sub-second precision you put it at.

**Comment by Aelazr** [comment]
Removed

**Pull request merged**
